import Header from '@/components/header'
import './globals.css'
import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'
import Providers from '@/context'

const roboto = Roboto({
  subsets: ['latin'],
  weight: ['300', '400', '500', '700'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: 'Bolpar',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br">
      <Providers>
        <body className={roboto.className}>
          <Header />
          <main className='flex justify-center pb-6'>
            {children}
          </main>
        </body>
      </Providers>
    </html>
  )
}
